"""Convert チュートリアル.xlsx (tutorial script) into data/tutorial.data.js.

Usage: python tools/tutorial_xlsx_to_js.py [path/to/チュートリアル.xlsx]
Input, first found: the argument, data/tutorial.xlsx, ~/Desktop/チュートリアル.xlsx.
Output: data/tutorial.data.js, a plain browser global (window.TUTORIAL_SERIFU) loaded via a normal
<script src> tag -- same reasoning as data/game.data.js (index.html must keep working from file://).

Only the セリフ column is exported for now (2026-09-28, per user request: "まずはセリフだけ反映されるように").
Row id = column A ("T001"...). A trailing line equal to the row's own id is a temporary checking mark
(per user request: "セリフの最後にT001のように付け足して ... 最終的には消します") and is stripped here,
so the marks can stay in the spreadsheet or be deleted without affecting the game.
Dev-time tool only; the game never reads xlsx directly.
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEST_JS = PROJECT_ROOT / "data" / "tutorial.data.js"
CANDIDATES = [
    PROJECT_ROOT / "data" / "tutorial.xlsx",
    Path.home() / "Desktop" / "チュートリアル.xlsx",
]
ID_PATTERN = re.compile(r"^T\d+$")


def find_source():
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    for path in CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("チュートリアル.xlsx が見つかりません: " + ", ".join(str(p) for p in CANDIDATES))


def clean_text(row_id, value):
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")
    if lines and lines[-1].strip() == row_id:
        lines.pop()
    elif lines and lines[0].strip() == row_id:
        lines.pop(0)
    return "\n".join(lines).strip(" \t\n")


def main():
    src = find_source()
    ws = openpyxl.load_workbook(src, data_only=True)["Sheet1"]
    header = {ws.cell(1, c).value: c for c in range(1, ws.max_column + 1) if ws.cell(1, c).value}
    if "セリフ" not in header:
        raise SystemExit("セリフ列が見つかりません")
    col = header["セリフ"]
    serifu = {}
    for r in range(2, ws.max_row + 1):
        row_id = ws.cell(r, 1).value
        value = ws.cell(r, col).value
        if not row_id or not ID_PATTERN.match(str(row_id)) or value is None:
            continue
        text = clean_text(str(row_id), value)
        if text:
            serifu[str(row_id)] = text
    body = json.dumps(serifu, ensure_ascii=False, indent=2)
    DEST_JS.write_text(
        "// Generated by tools/tutorial_xlsx_to_js.py from チュートリアル.xlsx -- do not edit by hand.\n"
        "window.TUTORIAL_SERIFU = " + body + ";\n",
        encoding="utf-8",
    )
    print(f"{len(serifu)} セリフ <- {src}\n-> {DEST_JS}")


if __name__ == "__main__":
    main()
