"""Convert チュートリアル.xlsx (tutorial script) into data/tutorial.data.js.

Usage: python tools/tutorial_xlsx_to_js.py [path/to/チュートリアル.xlsx]
Input, first found: the argument, data/tutorial.xlsx, ~/Desktop/チュートリアル.xlsx.
Output: data/tutorial.data.js, a plain browser global (window.TUTORIAL_SERIFU) loaded via a normal
<script src> tag -- same reasoning as data/game.data.js (index.html must keep working from file://).

Only the セリフ column is exported for now (2026-09-28, per user request: "まずはセリフだけ反映されるように").
Each row's text is keyed by its 実装ID column (= the step id in main.js's TUTORIAL_STEPS, e.g.
"game_rules_intro_1"), NOT by the row number in column A -- rows get inserted/renumbered in the spreadsheet
all the time, and a row-number key silently shifted every later line onto the wrong step (2026-09-29).
Rows with an empty 実装ID (new rows not implemented yet) are skipped. If the same 実装ID appears on more
than one row (the shared mis-click rescue line), the first row wins and a warning is printed if the
later rows' text differs.
A trailing line equal to the row's own id (T001...) is a temporary checking mark (per user request) and is
stripped here. Dev-time tool only; the game never reads xlsx directly.
"""
import json
import re
import sys
from pathlib import Path

import openpyxl

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DEST_JS = PROJECT_ROOT / "data" / "tutorial.data.js"
CANDIDATES = [
    PROJECT_ROOT / "data" / "tutorial.xlsx",
    Path.home() / "Desktop" / "チュートリアル.xlsx",
]


def find_source():
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    for path in CANDIDATES:
        if path.exists():
            return path
    raise SystemExit("チュートリアル.xlsx が見つかりません: " + ", ".join(str(p) for p in CANDIDATES))


def clean_text(row_id, value):
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    lines = text.split("\n")
    if lines and lines[-1].strip() == row_id:
        lines.pop()
    elif lines and lines[0].strip() == row_id:
        lines.pop(0)
    return "\n".join(lines).strip(" \t\n")


def main():
    src = find_source()
    ws = openpyxl.load_workbook(src, data_only=True)["Sheet1"]
    header = {ws.cell(1, c).value: c for c in range(1, ws.max_column + 1) if ws.cell(1, c).value}
    for needed in ("セリフ", "実装ID"):
        if needed not in header:
            raise SystemExit(f"{needed}列が見つかりません")
    text_col, id_col = header["セリフ"], header["実装ID"]
    serifu = {}
    first_row = {}
    skipped = []
    for r in range(2, ws.max_row + 1):
        row_id = ws.cell(r, 1).value
        value = ws.cell(r, text_col).value
        step_id = ws.cell(r, id_col).value
        if not row_id or value is None:
            continue
        text = clean_text(str(row_id), value)
        if not text:
            continue
        if not step_id or not str(step_id).strip():
            skipped.append(str(row_id))
            continue
        step_id = str(step_id).strip()
        if not re.fullmatch(r"[A-Za-z0-9_]+", step_id):
            raise SystemExit(f"{row_id}: 実装ID '{step_id}' が英数字とアンダースコア以外を含んでいます")
        if step_id in serifu:
            if serifu[step_id] != text:
                print(f"注意: 実装ID {step_id} が複数行にあり、セリフが違います({first_row[step_id]} を使い、{row_id} は無視)")
            continue
        serifu[step_id] = text
        first_row[step_id] = str(row_id)
    body = json.dumps(serifu, ensure_ascii=False, indent=2)
    DEST_JS.write_text(
        "// Generated by tools/tutorial_xlsx_to_js.py from チュートリアル.xlsx -- do not edit by hand.\n"
        "window.TUTORIAL_SERIFU = " + body + ";\n",
        encoding="utf-8",
    )
    print(f"{len(serifu)} セリフ(実装IDあり) <- {src}\n-> {DEST_JS}")
    if skipped:
        print("実装IDが空(ゲームにまだ無い行)のため読まなかった行:", ", ".join(skipped))


if __name__ == "__main__":
    main()
